apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: demo
  selector:
    app: demo
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  selector:
    matchLabels:
      app: demo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: wecs/demo:latest
        name: demo
        ports:
        - containerPort: 3000
          name: demo