# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:8.9
#      working_directory: ~/demo
#     steps:
#       - checkout
#       - setup_remote_docker
#       - restore_cache:
#           keys:
#           - v1-dependencies-{{ checksum "package.json" }}
#           - v1-dependencies-

#       - run:
#           name: Install node packages
#           command: |
#             npm install

#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}

#       - run:
#           name: Run tests
#           command: |
#             npm test

version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/workspace

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install node packages
          command: |
            yarn install
      
      - run:
          name: Start app
          command: |
            mkdir logs && yarn start &
      
      - run:
          name: Storing local IP address
          command: node -p "require('ip').address()" > logs/ip.log
      
      - run:
          name: Waiting for node server
          command: wget --retry-connrefused --waitretry=2 -t 5 "http://$(cat logs/ip.log):3000" > /dev/null

      - run:
          name: Run tests
          command: |
            yarn test
  
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}