version: 2
jobs:
  build:
    docker:
      - image: wecs/aws-k8s:1.0.0
    working_directory: ~/workspace
    environment:
      DEPLOYMENT_NAME: demo
      KOPS_STATE_STORE: cd.k8s.local

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install node packages
          command: |
            yarn install
      
      - run:
          name: Start app
          command: |
            yarn start &
      - run:
          name: Run tests
          command: |
            yarn test
      - run:
          name: Build docker
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo chmod +x ./deployment.sh && ./deployment.sh
            fi  
  
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  