# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:8.9
#      working_directory: ~/demo
#     steps:
#       - checkout
#       - setup_remote_docker
#       - restore_cache:
#           keys:
#           - v1-dependencies-{{ checksum "package.json" }}
#           - v1-dependencies-

#       - run:
#           name: Install node packages
#           command: |
#             npm install

#       - save_cache:
#           paths:
#             - node_modules
#           key: v1-dependencies-{{ checksum "package.json" }}

#       - run:
#           name: Run tests
#           command: |
#             npm test
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install node packages
          command: |
            yarn install
      
      - run:
          name: Start app
          command: |
            yarn start &

      - run:
          name: Run tests
          command: |
            yarn test
  
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # - run:
      #   	name: Build docker image
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #           - ./deployment.sh
			# 			fi